local function apply_func_powers(expr, name)
  local function powered_call(pow, arg)
    return string.format("(%s(%s))^(%s)", name, arg, pow)
  end

  -- \sin^{p}{x}, \sin^{p}(x)
  expr = expr:gsub("\\" .. name .. "%s*%^{([^}]+)}%s*{([^}]+)}", function(pow, arg)
    return powered_call(pow, arg)
  end)
  expr = expr:gsub("\\" .. name .. "%s*%^{([^}]+)}%s*%(([^)]+)%)", function(pow, arg)
    return powered_call(pow, arg)
  end)
  -- \sin^p{x}, \sin^p(x)
  expr = expr:gsub("\\" .. name .. "%s*%^%s*(%d+)%s*{([^}]+)}", function(pow, arg)
    return powered_call(pow, arg)
  end)
  expr = expr:gsub("\\" .. name .. "%s*%^%s*(%d+)%s*%(([^)]+)%)", function(pow, arg)
    return powered_call(pow, arg)
  end)
  -- \sin^{p}x, \sin^p x (simple token args)
  expr = expr:gsub("\\" .. name .. "%s*%^{([^}]+)}%s*\\pi", function(pow)
    return powered_call(pow, "pi")
  end)
  expr = expr:gsub("\\" .. name .. "%s*%^%s*(%d+)%s*\\pi", function(pow)
    return powered_call(pow, "pi")
  end)
  expr = expr:gsub("\\" .. name .. "%s*%^{([^}]+)}%s*([%a_][%w_]*)", function(pow, arg)
    return powered_call(pow, arg)
  end)
  expr = expr:gsub("\\" .. name .. "%s*%^%s*(%d+)%s*([%a_][%w_]*)", function(pow, arg)
    return powered_call(pow, arg)
  end)
  expr = expr:gsub("\\" .. name .. "%s*%^{([^}]+)}%s*(%d+%.?%d*)", function(pow, arg)
    return powered_call(pow, arg)
  end)
  expr = expr:gsub("\\" .. name .. "%s*%^%s*(%d+)%s*(%d+%.?%d*)", function(pow, arg)
    return powered_call(pow, arg)
  end)
  return expr
end

return apply_func_powers
